/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyBackdrop {}
  interface MyModal {
    'content': string;
    'open': () => Promise<void>;
    'title': string;
  }
}

declare global {


  interface HTMLMyBackdropElement extends Components.MyBackdrop, HTMLStencilElement {}
  var HTMLMyBackdropElement: {
    prototype: HTMLMyBackdropElement;
    new (): HTMLMyBackdropElement;
  };

  interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {}
  var HTMLMyModalElement: {
    prototype: HTMLMyModalElement;
    new (): HTMLMyModalElement;
  };
  interface HTMLElementTagNameMap {
    'my-backdrop': HTMLMyBackdropElement;
    'my-modal': HTMLMyModalElement;
  }
}

declare namespace LocalJSX {
  interface MyBackdrop extends JSXBase.HTMLAttributes<HTMLMyBackdropElement> {}
  interface MyModal extends JSXBase.HTMLAttributes<HTMLMyModalElement> {
    'content'?: string;
    'title'?: string;
  }

  interface IntrinsicElements {
    'my-backdrop': MyBackdrop;
    'my-modal': MyModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


